name: Python CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  test-log-analyzer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.9" # Ta version exacte

      - name: Installation des dépendances
        run: |
          python -m pip install --upgrade pip
          pip install colorama  # si ton script utilise cette lib

      - name: Exécution du script log-analyzer
        run: |
          python log-analyzer.py
